// Credits : @knoxy_dev
#pragma once

#include "SDK.hpp"

inline void DisableAntiCheatManager(SDK::UPlayerAntiCheatManager* acm)
{
    if (!acm || SDK::isObjectInvalid(acm)) return;

    acm->bReportFeedBack = false;
    acm->bOpenDetailDataCollect = false;
    acm->bOpenBaseDiffCheck = false;
    acm->bUploadStuckGroundCount = false;

    acm->MaxShootPointPassWall = 999999;
    acm->MaxMuzzleHeightTime = 999999;
    acm->MaxLocusFailTime = 999999;
    acm->MaxBulletVictimClientPassWallTimes = 999999;
    acm->MaxGunPosErrorTimes = 999999;
    acm->MaxAllowVehicleTimeSpeedRawTime = 999999;
    acm->MaxAllowVehicleTimeSpeedConvTime = 999999;
    acm->MaxAllowVehicleAccTime = 999999;

    auto BlackoutSwitch = [](SDK::FVerifySwitch& sw) {
        *(int*)((uintptr_t)&sw + 0x0008) = 999999;
        *(bool*)((uintptr_t)&sw + 0x000D) = false;
        *(int*)((uintptr_t)&sw + 0x0010) = 0;
    };

    BlackoutSwitch(acm->VsNoHitDetail);
    BlackoutSwitch(acm->VsMuzzleRangeCircle);
    BlackoutSwitch(acm->VsMuzzleRangeUp);
    BlackoutSwitch(acm->VsHitBoneNameNone);
    BlackoutSwitch(acm->VsHitBoneHitMissMatch);
    BlackoutSwitch(acm->VsBulletID);
    BlackoutSwitch(acm->VsVehicleTimeStampError);
    BlackoutSwitch(acm->VsWatchTimeStampError);
    BlackoutSwitch(acm->VsBoneInfo);
    BlackoutSwitch(acm->VsJumpMaxHeight);
    BlackoutSwitch(acm->VsJumpMaxHeight15);
    BlackoutSwitch(acm->VsJumpMaxHeight2);
    BlackoutSwitch(acm->VsShootRpgShootTimeVerify);
    BlackoutSwitch(acm->VsShootLockShootTimeVerify);
    BlackoutSwitch(acm->VsShootRpgHitNewVerify);
    BlackoutSwitch(acm->VsShootTimeConDelta);
    BlackoutSwitch(acm->VsServerNoOldShoot);
    BlackoutSwitch(acm->VsClientNotConnectShoot);
    BlackoutSwitch(acm->VsShootRpgShootIntervalVerify);
    BlackoutSwitch(acm->VsImpactPointAndBulletDisBig);
    BlackoutSwitch(acm->VsShootVerifyInvalid);
    BlackoutSwitch(acm->VsImpactActorPosWithNoHisPos);
    BlackoutSwitch(acm->FarJump);
    BlackoutSwitch(acm->VsShootAngleInVaild);
    BlackoutSwitch(acm->VsMuzzleAndTailPosInVaild);
    BlackoutSwitch(acm->VsMuzzleAndImpactPassWall);
    BlackoutSwitch(acm->VsMuzzleAndTailPassWall);
    BlackoutSwitch(acm->VsImpactActorPosOffsetBig);
    BlackoutSwitch(acm->VsImpactPointChangeSmall);
    BlackoutSwitch(acm->VsImpactBulletPosOffsetBig);
    BlackoutSwitch(acm->VsTotalImactCharacterNum);
    BlackoutSwitch(acm->ClientTimeSpeedAcc);
    BlackoutSwitch(acm->ServerAccumulateErrorReplay);
    BlackoutSwitch(acm->DSSpeedOver10FailedCnt);
    BlackoutSwitch(acm->DSSpeedOver15FailedCnt);
    BlackoutSwitch(acm->DSSpeedOver20FailedCnt);
    BlackoutSwitch(acm->SpeedQuickCheck);
    BlackoutSwitch(acm->BulletDirError);
    BlackoutSwitch(acm->SwitchMuzzleLocusError);
    BlackoutSwitch(acm->SwitchMuzzleLocusErrorX);
    BlackoutSwitch(acm->SwitchMuzzleLocusErrorY);
    BlackoutSwitch(acm->SwitchMuzzleLocusErrorZ);
    BlackoutSwitch(acm->Gun2ShooterPosError1);
    BlackoutSwitch(acm->SwitchHeadLocusError3);
    BlackoutSwitch(acm->SwitchMuzzleLocusErrorLength);
    BlackoutSwitch(acm->SwitchShootPosHistoryLocusError3);
    BlackoutSwitch(acm->SwitchHitComponentUnvalid);
    BlackoutSwitch(acm->SwitchHitNoRender);
    BlackoutSwitch(acm->SwitchHitOutCollisionBox);
    BlackoutSwitch(acm->HeadOverShootPos);
    BlackoutSwitch(acm->SwitchMuzzleImpactDirSkipPunish1);
    BlackoutSwitch(acm->SwitchInvalidBulletNumInBarrel);
    BlackoutSwitch(acm->SwitchShooterMovementError2);
    BlackoutSwitch(acm->GunTailPosError);
    BlackoutSwitch(acm->SwitchMuzzleImpactDirSkipPunish2);
    BlackoutSwitch(acm->SwitchMuzzleImpactDirError1);
    BlackoutSwitch(acm->SwitchMuzzleImpactDirError2);
    BlackoutSwitch(acm->ShooterHead2PosBlock);
    BlackoutSwitch(acm->SwitchShootPosHistoryLocusError2);
    BlackoutSwitch(acm->Head2GunTailPosError1);
    BlackoutSwitch(acm->SwitchShootDirExcepation1);
    BlackoutSwitch(acm->SwitchShootDirExcepation2);
    BlackoutSwitch(acm->SwitchCamerModeException);
    BlackoutSwitch(acm->SwitchShootPosHistoryLocusError4);
    BlackoutSwitch(acm->SwitchMuzzleImpactDirError3);
    BlackoutSwitch(acm->CharacterMoveException1);
    BlackoutSwitch(acm->CharacterMoveException2);
    BlackoutSwitch(acm->CharacterMoveException3);
    BlackoutSwitch(acm->CharacterMoveException4);
    BlackoutSwitch(acm->CharacterMoveException5);
    BlackoutSwitch(acm->CharacterMoveException6);
    BlackoutSwitch(acm->VehicleSpeedZDeltaOver10TimesWhenNoXY);
    BlackoutSwitch(acm->VehicleVelZCheck1);
    BlackoutSwitch(acm->VehicleVelZCheck2);
    BlackoutSwitch(acm->VehicleMaxSpeedCheck);
    BlackoutSwitch(acm->VehicleHitMuzzleCheck);
    BlackoutSwitch(acm->VehicleHitImpactPointCheck);
    BlackoutSwitch(acm->VehicleHitBlockWall);
    BlackoutSwitch(acm->VehicleSidesway1);
    BlackoutSwitch(acm->VehicleSidesway2);
    BlackoutSwitch(acm->FarShootInMidAirVehicleExceedThreshold);
    BlackoutSwitch(acm->FarShootInMidAirVehicleEnemyDistanceTrial);
    BlackoutSwitch(acm->FarShootInMidAirVehicleEnemyDistanceFurtherTrial);
    BlackoutSwitch(acm->FarShootInMidAirVehicleHeightTrial);
    BlackoutSwitch(acm->FarShootInMidAirVehicleHeightFurtherTrial);
    BlackoutSwitch(acm->FarShootInMidAirPawnExceedThreshold);
    BlackoutSwitch(acm->FarShootInMidAirPawnEnemyDistanceTrial);
    BlackoutSwitch(acm->FarShootInMidAirPawnEnemyDistanceFurtherTrial);
    BlackoutSwitch(acm->FarShootInMidAirPawnHeightTrial);
    BlackoutSwitch(acm->FarShootInMidAirPawnHeightFurtherTrial);
    BlackoutSwitch(acm->DSRunning2DSpeedExceededCount);
    BlackoutSwitch(acm->DSRunning2DSpeedTrial);
    BlackoutSwitch(acm->DSRunning2DSpeedFurtherTrial);
    BlackoutSwitch(acm->DSIgnoreNetworkDying2DSpeedExceededCount);
    BlackoutSwitch(acm->DSDyingMoveSpeedExceedCount);
    BlackoutSwitch(acm->NonGunADSFarShootCount);
    BlackoutSwitch(acm->NonGunADSFarShootFromClientBulletDataCount);
    BlackoutSwitch(acm->NonGunADSFarShootFromClientBulletDataEnemyDistanceTrialCount);
    BlackoutSwitch(acm->NonGunADSFarShootFromClientBulletDataEnemyDistanceFurtherTrialCount);
    BlackoutSwitch(acm->ClientUploadFuzzyObjectVerifyFail);
    BlackoutSwitch(acm->ClientMoveTimeStampResetFrequencyExceedThreshold);
    BlackoutSwitch(acm->ShootBirdNonGunADSExceedThreshold);
    BlackoutSwitch(acm->ShootBirdNonGunADSDistanceTrial);
    BlackoutSwitch(acm->ShootBirdNonGunADSDistanceFurtherTrial);
    BlackoutSwitch(acm->FarShootInHighTangentMoveSpeedExceedThreshold);
    BlackoutSwitch(acm->FarShootInHighTangentMoveSpeedEnemyDistanceTrial);
    BlackoutSwitch(acm->FarShootInHighTangentMoveSpeedEnemyDistanceFurtherTrial);
    BlackoutSwitch(acm->FarShootInHighTangentMoveSpeedSpeedTrial);
    BlackoutSwitch(acm->FarShootInHighTangentMoveSpeedSpeedFurtherTrial);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireAfterKill);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireAfterKillDistanceTrial);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireAfterKillTimeTrial);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireAfterKillMaxTime);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFirePickUpItem);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFirePickUpItemDistanceTrial);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFirePickUpItemTimeTrial);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFirePickUpItemMaxTime);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireNotKill);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireNotKillDistanceTrial);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireNotKillTimeTrial);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireNotKillMaxTime);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireOnVehicle);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireOnVehicleDistanceTrial);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireOnVehicleTimeTrial);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireOnVehicleMaxTime);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireSameVehicle);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireSameVehicleTimeTrial);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireSameVehicleMaxTime);
    BlackoutSwitch(acm->IllegalTeamUpUseObjectTogether);
    BlackoutSwitch(acm->IllegalTeamUpGetOnEnemyVehicleCount);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireOneSideHasWeaponOnFoot);
    BlackoutSwitch(acm->IllegalTeamUpNearbyButNoFireOneSideHasWeaponOnFootDistanceTrial);
    BlackoutSwitch(acm->IllegalTeamUpStayOnEnemyVehicle);
    BlackoutSwitch(acm->KillBird);
    BlackoutSwitch(acm->ParachuteLandingSecondsExceedThreshold);
    BlackoutSwitch(acm->ParachuteObliqueLandingSecondsExceedThreshold);
    BlackoutSwitch(acm->ShootBird);
    BlackoutSwitch(acm->DSFallingSpeedFailCount);
    BlackoutSwitch(acm->DSFallingHeightFailCount);
    BlackoutSwitch(acm->ShooterCapsuleCollided);
    BlackoutSwitch(acm->JumpReviewHighJumpExceed);
    BlackoutSwitch(acm->JumpReviewFarJumpExceed);
    BlackoutSwitch(acm->JumpReviewLowerFarJump);
    BlackoutSwitch(acm->SmallActorTimeDilationCount);
    BlackoutSwitch(acm->LargeRotateLockShooting);
    BlackoutSwitch(acm->SmallRotateLockShooting);
    BlackoutSwitch(acm->OneClipShootCount);
    BlackoutSwitch(acm->ClientWeaponFastReload);
    BlackoutSwitch(acm->WalkSpeedFailedCnt);
    BlackoutSwitch(acm->DSCheckClientTimeMoveDistance2D);
    BlackoutSwitch(acm->DSCheckClientTimeMoveDistance2DTrial);
    BlackoutSwitch(acm->DSCheckClientTimeMoveDistance2DFurther);
    BlackoutSwitch(acm->DSCheckClientTimeMoveDistanceZ);
    BlackoutSwitch(acm->DSCheckClientTimeMoveDistanceZTrial);
    BlackoutSwitch(acm->DSCheckClientTimeMoveDistanceZFurther);
    BlackoutSwitch(acm->ReplayMaxFallingSustainTime);
    BlackoutSwitch(acm->ReplayMaxCustomMoveModeSustainTime);
    BlackoutSwitch(acm->ReplayMaxSingleShotDamage);
    BlackoutSwitch(acm->UndergroundCount);
    BlackoutSwitch(acm->MoveDistance2DPerSecondAnomaly);
    BlackoutSwitch(acm->CharMoveDist2DPerSecondAnomaly);
    BlackoutSwitch(acm->CharMoveDist2DPerSecondCount);
    BlackoutSwitch(acm->CharMoveAccumDist2D_DS);
    BlackoutSwitch(acm->CharMoveAccumDist3D_DS);
    BlackoutSwitch(acm->CharMoveAccumDist2D_Client);
    BlackoutSwitch(acm->CharMoveAccumDist3D_Client);
    BlackoutSwitch(acm->CharMoveAccumDist2D_ClientAll);
    BlackoutSwitch(acm->CharMoveAccumDist3D_ClientAll);
    BlackoutSwitch(acm->DistanceToGroundAnomaly);
    BlackoutSwitch(acm->SingleShotDamageAnomaly);
    BlackoutSwitch(acm->BandaCount);
    BlackoutSwitch(acm->MetroEnterRadiationTime);
    BlackoutSwitch(acm->MetroEnterRadiationTimeTrial);
    BlackoutSwitch(acm->MetroLeaveBornObstacle);
    BlackoutSwitch(acm->VsPetJumpHeightLimiter);
    BlackoutSwitch(acm->VsPetMoveSpeedLimiter);
    BlackoutSwitch(acm->VsBioVehicleMoveSpeedLimiter);
    BlackoutSwitch(acm->VsBioVehicleJumpHeightLimiter);
    BlackoutSwitch(acm->VsPterosaurFlyVehicleSpeed);
    BlackoutSwitch(acm->VsBioVehicleGravityLimiter);
    BlackoutSwitch(acm->ServerMoveCacheCountOver);
    BlackoutSwitch(acm->ServerMoveCacheCountOver3d);
    BlackoutSwitch(acm->ServerMoveBurst);
    BlackoutSwitch(acm->ImpactOtherAfterBurst);
    BlackoutSwitch(acm->KillOtherAfterBurst);
    BlackoutSwitch(acm->PickupAfterBurst);
    BlackoutSwitch(acm->ContinueMoveBurst);
    BlackoutSwitch(acm->VerifySwitchCameraRotation);
    BlackoutSwitch(acm->VerifySwitchPeekShootThroughWall);
    BlackoutSwitch(acm->VerifySwitchCameraLocation);
    BlackoutSwitch(acm->VerifySwitchAutoAimByLockView);
    BlackoutSwitch(acm->VerifySwitchControlRotation);
    BlackoutSwitch(acm->VerifySwitchRecoilFaildCount);
    BlackoutSwitch(acm->VerifySwitchMarcoPolo);
    BlackoutSwitch(acm->VerifySwitchMarcoPolo2);
    BlackoutSwitch(acm->VerifySwitchMarcoPolo3);
    BlackoutSwitch(acm->VerifySwitchMeshScaleDiff);
    BlackoutSwitch(acm->VerifySwitchOfflineMove);
    BlackoutSwitch(acm->VerifySwitchFastAimShootHit);
    BlackoutSwitch(acm->VerifySwitchNoRecoilOnWeaponShoot);
    BlackoutSwitch(acm->VerifySwitchLessRecoilOnWeaponShoot);
    BlackoutSwitch(acm->VerifySwitchNoRecoilOnKickBack);
    BlackoutSwitch(acm->VerifySwitchLessRecoilOnKickBack);
    BlackoutSwitch(acm->VerifySwitchDivingBoost);
    BlackoutSwitch(acm->VerifySwitchRecoilCurveFailed);
    BlackoutSwitch(acm->PlayerQuickProne);
    BlackoutSwitch(acm->BaseDiffSample);
    BlackoutSwitch(acm->ServerMoveTimeStamp);
    BlackoutSwitch(acm->ServerMoveAccel);
    BlackoutSwitch(acm->ServerMoveClientLoc);
    BlackoutSwitch(acm->ServerMoveCompressedMoveFlags);
    BlackoutSwitch(acm->ServerMoveClientRoll);
    BlackoutSwitch(acm->ServerMoveView);
    BlackoutSwitch(acm->ServerMoveClientMovementBase);
    BlackoutSwitch(acm->ServerMoveClientBaseBoneName);
    BlackoutSwitch(acm->ServerMoveClientMovementMode);
    BlackoutSwitch(acm->PlayerInstantHeightDiff);
    BlackoutSwitch(acm->Player2SecHeightDiff);
    BlackoutSwitch(acm->VsTeammateRescue);
    BlackoutSwitch(acm->VsTeammateRescueVictim);
    BlackoutSwitch(acm->VsTeammateRecall);
    BlackoutSwitch(acm->VsTeammateRecallVictim);
    BlackoutSwitch(acm->VsAutoClicker);
    BlackoutSwitch(acm->VsAbnormalShootingRotation);
}
